# Generated by Django 5.1.3 on 2024-12-02 08:53

from django.db import migrations, models
from django.contrib.auth.models import User


def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin').exists():
        try:
            User.objects.create_superuser(
                username='admin',
                email='admin@example.com',
                password='admin123'
            )
            print("Superuser admin berhasil dibuat.")
        except Exception as e:
            print(f"Error membuat superuser: {e}")
    else:
        print("Superuser admin sudah ada.")

def remove_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='admin').delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_input', models.CharField(max_length=4)),
                ('jenis_dokumen', models.CharField(max_length=50)),
                ('tahun_anggaran', models.DateField()),
                ('judul_dokumen', models.CharField(max_length=255)),
                ('status_dokumen', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='dokumen/')),
            ],
            options={
                'verbose_name': 'Dokumen',
                'verbose_name_plural': 'Dokumen',
                'db_table': 'dokumen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_input', models.CharField(max_length=4)),
                ('jenis_dokumen', models.CharField(max_length=50)),
                ('tahun_anggaran', models.DateField()),
                ('judul_dokumen', models.CharField(max_length=255)),
                ('status_dokumen', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Form Data',
                'verbose_name_plural': 'Form Data',
                'db_table': 'form_data',
                'managed': True,
            },
        ),
        migrations.RunPython(create_superuser, remove_superuser),
    ]
