# Generated by Django 5.1.3 on 2024-12-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_formdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/'),
        ),
    ]
