# Generated by Django 5.0.6 on 2024-12-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_formdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_input', models.CharField(max_length=4)),
                ('jenis_dokumen', models.CharField(max_length=50)),
                ('tahun_anggaran', models.DateField()),
                ('judul_dokumen', models.CharField(max_length=255)),
                ('status_dokumen', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Form Data',
                'verbose_name_plural': 'Form Data',
                'db_table': 'form_data',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/'),
        ),
    ]
