# Generated by Django 3.2.6 on 2024-12-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20241223_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='kode_input',
            field=models.CharField(max_length=25),
        ),
    ]
