# Generated by Django 5.0.6 on 2024-12-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_formdata_alter_dokumen_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
