# Generated by Django 5.1.3 on 2024-12-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_dokumen_file'),
        ('home', '0004_alter_dokumen_kode_input'),
    ]

    operations = [
    ]
